CREATE TABLE account(
    contact_id INT,
    type_ VARCHAR(255),
    created_at VARCHAR(255),
    browser_type VARCHAR(255),
    ip_address VARCHAR(255),
    total_pages VARCHAR(255),
    total_time VARCHAR(255),
    total_visits VARCHAR(255),
    name_ VARCHAR(255),
    first_page_in_visit VARCHAR(255),
    last_page_in_visit VARCHAR(255),
    time_zone VARCHAR(255),
    country_from_ip INT(255),
    country_name VARCHAR(255),
    isp_from_ip INT(255),
    province_from_ip INT,
    type_ VARCHAR(255),
    created_at VARCHAR(255),
    browser_type VARCHAR(255),
    ip_address VARCHAR(255)
    );